name: Node.js CI

on:
  push:
    branches: [ "main" ]
permissions:
  pages: write      # to deploy to Pages
  id-token: write
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build # Use Vite build
      - name: upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
         name: 'github-pages'
         path: build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts_name: 'github-pages'



